modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="skyblue"
version="0.0.1"
displayName="skyblue"
displayURL="https://www.curseforge.com/minecraft/mc-mods"
logoFile="logo.png"
credits="made by Floi"
authors="Floi"
description="dreams"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.skyblue]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration
