/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.skyblue.init;

import net.skyblue.item.*;
import net.skyblue.SkyblueMod;

import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.RegistryObject;

import net.minecraft.item.TallBlockItem;
import net.minecraft.item.Rarity;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.Item;
import net.minecraft.item.BlockItem;
import net.minecraft.block.Block;

public class SkyblueModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, SkyblueMod.MODID);
	public static final RegistryObject<Item> SIXTHREE;
	public static final RegistryObject<Item> SEVENZERO;
	public static final RegistryObject<Item> FOURTWO;
	public static final RegistryObject<Item> FOURTHREE;
	public static final RegistryObject<Item> NINEEIGHT;
	public static final RegistryObject<Item> NINE;
	public static final RegistryObject<Item> FOURNINE;
	public static final RegistryObject<Item> ONEZEROFIVE;
	public static final RegistryObject<Item> ONEFOURTWO;
	public static final RegistryObject<Item> ONETHREEFOUR;
	public static final RegistryObject<Item> ONETHREENOE;
	public static final RegistryObject<Item> ONEONETWO;
	public static final RegistryObject<Item> TWOFIVESIX;
	public static final RegistryObject<Item> TWOFOUR;
	public static final RegistryObject<Item> ONEZERONINE;
	public static final RegistryObject<Item> ONEFIVE;
	public static final RegistryObject<Item> SKYKEY;
	public static final RegistryObject<Item> AB_1;
	public static final RegistryObject<Item> AB_2;
	public static final RegistryObject<Item> AB_3;
	public static final RegistryObject<Item> AB_4;
	public static final RegistryObject<Item> AB_5;
	public static final RegistryObject<Item> AB_6;
	public static final RegistryObject<Item> AB_7;
	public static final RegistryObject<Item> AB_8;
	public static final RegistryObject<Item> AB_9;
	public static final RegistryObject<Item> AB_10;
	public static final RegistryObject<Item> AB_11;
	public static final RegistryObject<Item> AB_12;
	public static final RegistryObject<Item> AB_13;
	public static final RegistryObject<Item> AB_14;
	public static final RegistryObject<Item> AB_15;
	public static final RegistryObject<Item> AB_16;
	public static final RegistryObject<Item> AB_17;
	public static final RegistryObject<Item> AB_18;
	public static final RegistryObject<Item> AB_19;
	public static final RegistryObject<Item> AB_20;
	public static final RegistryObject<Item> AB_21;
	public static final RegistryObject<Item> AB_22;
	public static final RegistryObject<Item> AB_23;
	public static final RegistryObject<Item> AB_24;
	public static final RegistryObject<Item> ONETWONINE;
	public static final RegistryObject<Item> NORMALSKY;
	public static final RegistryObject<Item> ABB;
	public static final RegistryObject<Item> DD_1;
	public static final RegistryObject<Item> DD_2;
	public static final RegistryObject<Item> D_1R;
	public static final RegistryObject<Item> EWATER_BUCKET;
	public static final RegistryObject<Item> EGRASS;
	public static final RegistryObject<Item> EDIRT;
	public static final RegistryObject<Item> ESTONE;
	public static final RegistryObject<Item> EE_1;
	public static final RegistryObject<Item> FT_1;
	public static final RegistryObject<Item> FRR_1;
	public static final RegistryObject<Item> FFR;
	public static final RegistryObject<Item> GREEN;
	public static final RegistryObject<Item> RED_1;
	public static final RegistryObject<Item> GG_1;
	public static final RegistryObject<Item> RED_2;
	public static final RegistryObject<Item> GREEN_2;
	public static final RegistryObject<Item> GG_2;
	public static final RegistryObject<Item> GREEN_3;
	public static final RegistryObject<Item> RED_3;
	public static final RegistryObject<Item> GG_3;
	public static final RegistryObject<Item> GREEN_4;
	public static final RegistryObject<Item> RED_4;
	public static final RegistryObject<Item> GG_4;
	public static final RegistryObject<Item> GG_5;
	public static final RegistryObject<Item> GREEN_5;
	public static final RegistryObject<Item> RED_5;
	public static final RegistryObject<Item> PHOTO_1;
	public static final RegistryObject<Item> WATERH_BUCKET;
	public static final RegistryObject<Item> MUSH_1;
	public static final RegistryObject<Item> BLUE_1;
	public static final RegistryObject<Item> BLUE_2;
	public static final RegistryObject<Item> BLUE_3;
	public static final RegistryObject<Item> BLUE_4;
	public static final RegistryObject<Item> BLUE_5;
	public static final RegistryObject<Item> TWOTHREETWO;
	public static final RegistryObject<Item> I_LOG;
	public static final RegistryObject<Item> I_WOOD;
	public static final RegistryObject<Item> I_PLANKS;
	public static final RegistryObject<Item> I_LEAVES;
	public static final RegistryObject<Item> I_STAIRS;
	public static final RegistryObject<Item> I_SLAB;
	public static final RegistryObject<Item> I_FENCE;
	public static final RegistryObject<Item> I_FENCE_GATE;
	public static final RegistryObject<Item> I_PRESSURE_PLATE;
	public static final RegistryObject<Item> I_BUTTON;
	public static final RegistryObject<Item> ICOBBLESTONE;
	public static final RegistryObject<Item> IDOORS;
	public static final RegistryObject<Item> ICOBBLESTONE_STAIRS;
	public static final RegistryObject<Item> IP;
	public static final RegistryObject<Item> JB_1;
	public static final RegistryObject<Item> JP;
	public static final RegistryObject<Item> JP_2;
	public static final RegistryObject<Item> JP_3;
	public static final RegistryObject<Item> JP_4;
	public static final RegistryObject<Item> JB_2SEVENONE;
	public static final RegistryObject<Item> KK_1;
	public static final RegistryObject<Item> KK_2;
	public static final RegistryObject<Item> KK_3;
	public static final RegistryObject<Item> KK_1_ONE_EIGHT_EIGHT;
	public static final RegistryObject<Item> K_KBRICK;
	public static final RegistryObject<Item> K_KFLOOR;
	public static final RegistryObject<Item> LL_1SNOW;
	public static final RegistryObject<Item> LL_1ROCK;
	public static final RegistryObject<Item> LWATER_BUCKET;
	public static final RegistryObject<Item> L_LOG;
	public static final RegistryObject<Item> L_WOOD;
	public static final RegistryObject<Item> L_PLANKS;
	public static final RegistryObject<Item> L_LEAVES;
	public static final RegistryObject<Item> L_STAIRS;
	public static final RegistryObject<Item> L_SLAB;
	public static final RegistryObject<Item> L_FENCE;
	public static final RegistryObject<Item> L_FENCE_GATE;
	public static final RegistryObject<Item> L_PRESSURE_PLATE;
	public static final RegistryObject<Item> L_BUTTON;
	public static final RegistryObject<Item> LSAP;
	public static final RegistryObject<Item> LW;
	public static final RegistryObject<Item> MMMMMMM;
	public static final RegistryObject<Item> SHARD_14;
	public static final RegistryObject<Item> MMP;
	public static final RegistryObject<Item> NNN;
	public static final RegistryObject<Item> NWATER_BUCKET;
	public static final RegistryObject<Item> NLOG;
	public static final RegistryObject<Item> NLOG_SLAB;
	public static final RegistryObject<Item> OC;
	public static final RegistryObject<Item> OPLATE_1;
	public static final RegistryObject<Item> OROCK_1;
	public static final RegistryObject<Item> OROCK_2;
	public static final RegistryObject<Item> OROCK_3;
	public static final RegistryObject<Item> OO;
	public static final RegistryObject<Item> O_CC;
	public static final RegistryObject<Item> PP;
	public static final RegistryObject<Item> ONETWOFIVE;
	static {
		SIXTHREE = blockCMT(SkyblueModBlocks.SIXTHREE, SkyblueModTabs.TAB_SKYBLUE);
		SEVENZERO = blockCMT(SkyblueModBlocks.SEVENZERO, SkyblueModTabs.TAB_SKYBLUE);
		FOURTWO = blockCMT(SkyblueModBlocks.FOURTWO, SkyblueModTabs.TAB_SKYBLUE);
		FOURTHREE = blockCMT(SkyblueModBlocks.FOURTHREE, SkyblueModTabs.TAB_SKYBLUE);
		NINEEIGHT = blockCMT(SkyblueModBlocks.NINEEIGHT, SkyblueModTabs.TAB_SKYBLUE);
		NINE = blockCMT(SkyblueModBlocks.NINE, SkyblueModTabs.TAB_SKYBLUE);
		FOURNINE = blockCMT(SkyblueModBlocks.FOURNINE, SkyblueModTabs.TAB_SKYBLUE);
		ONEZEROFIVE = blockCMT(SkyblueModBlocks.ONEZEROFIVE, SkyblueModTabs.TAB_SKYBLUE);
		ONEFOURTWO = blockCMT(SkyblueModBlocks.ONEFOURTWO, SkyblueModTabs.TAB_SKYBLUE);
		ONETHREEFOUR = blockCMT(SkyblueModBlocks.ONETHREEFOUR, SkyblueModTabs.TAB_SKYBLUE);
		ONETHREENOE = blockCMT(SkyblueModBlocks.ONETHREENOE, SkyblueModTabs.TAB_SKYBLUE);
		ONEONETWO = blockCMT(SkyblueModBlocks.ONEONETWO, SkyblueModTabs.TAB_SKYBLUE);
		TWOFIVESIX = blockCMT(SkyblueModBlocks.TWOFIVESIX, SkyblueModTabs.TAB_SKYBLUE);
		TWOFOUR = blockCMT(SkyblueModBlocks.TWOFOUR, SkyblueModTabs.TAB_SKYBLUE);
		ONEZERONINE = blockCMT(SkyblueModBlocks.ONEZERONINE, SkyblueModTabs.TAB_SKYBLUE);
		ONEFIVE = blockCMT(SkyblueModBlocks.ONEFIVE, SkyblueModTabs.TAB_SKYBLUE);
		SKYKEY = REGISTRY.register("skykey", SkykeyItem::new);
		AB_1 = blockCMT(SkyblueModBlocks.AB_1, SkyblueModTabs.TAB_SKYBLUE);
		AB_2 = blockCMT(SkyblueModBlocks.AB_2, SkyblueModTabs.TAB_SKYBLUE);
		AB_3 = blockCMT(SkyblueModBlocks.AB_3, SkyblueModTabs.TAB_SKYBLUE);
		AB_4 = blockCMT(SkyblueModBlocks.AB_4, SkyblueModTabs.TAB_SKYBLUE);
		AB_5 = blockCMT(SkyblueModBlocks.AB_5, SkyblueModTabs.TAB_SKYBLUE);
		AB_6 = blockCMT(SkyblueModBlocks.AB_6, SkyblueModTabs.TAB_SKYBLUE);
		AB_7 = blockCMT(SkyblueModBlocks.AB_7, SkyblueModTabs.TAB_SKYBLUE);
		AB_8 = blockCMT(SkyblueModBlocks.AB_8, SkyblueModTabs.TAB_SKYBLUE);
		AB_9 = blockCMT(SkyblueModBlocks.AB_9, SkyblueModTabs.TAB_SKYBLUE);
		AB_10 = blockCMT(SkyblueModBlocks.AB_10, SkyblueModTabs.TAB_SKYBLUE);
		AB_11 = blockCMT(SkyblueModBlocks.AB_11, SkyblueModTabs.TAB_SKYBLUE);
		AB_12 = blockCMT(SkyblueModBlocks.AB_12, SkyblueModTabs.TAB_SKYBLUE);
		AB_13 = blockCMT(SkyblueModBlocks.AB_13, SkyblueModTabs.TAB_SKYBLUE);
		AB_14 = blockCMT(SkyblueModBlocks.AB_14, SkyblueModTabs.TAB_SKYBLUE);
		AB_15 = blockCMT(SkyblueModBlocks.AB_15, SkyblueModTabs.TAB_SKYBLUE);
		AB_16 = blockCMT(SkyblueModBlocks.AB_16, SkyblueModTabs.TAB_SKYBLUE);
		AB_17 = blockCMT(SkyblueModBlocks.AB_17, SkyblueModTabs.TAB_SKYBLUE);
		AB_18 = blockCMT(SkyblueModBlocks.AB_18, SkyblueModTabs.TAB_SKYBLUE);
		AB_19 = blockCMT(SkyblueModBlocks.AB_19, SkyblueModTabs.TAB_SKYBLUE);
		AB_20 = blockCMT(SkyblueModBlocks.AB_20, SkyblueModTabs.TAB_SKYBLUE);
		AB_21 = blockCMT(SkyblueModBlocks.AB_21, SkyblueModTabs.TAB_SKYBLUE);
		AB_22 = blockCMT(SkyblueModBlocks.AB_22, SkyblueModTabs.TAB_SKYBLUE);
		AB_23 = blockCMT(SkyblueModBlocks.AB_23, SkyblueModTabs.TAB_SKYBLUE);
		AB_24 = blockCMT(SkyblueModBlocks.AB_24, SkyblueModTabs.TAB_SKYBLUE);
		ONETWONINE = blockCMT(SkyblueModBlocks.ONETWONINE, SkyblueModTabs.TAB_SKYBLUE);
		NORMALSKY = REGISTRY.register("normalsky", NormalskyItem::new);
		ABB = blockCMT(SkyblueModBlocks.ABB, SkyblueModTabs.TAB_SKYBLUE);
		DD_1 = blockCMT(SkyblueModBlocks.DD_1, SkyblueModTabs.TAB_SKYBLUE);
		DD_2 = blockCMT(SkyblueModBlocks.DD_2, SkyblueModTabs.TAB_SKYBLUE);
		D_1R = blockCMT(SkyblueModBlocks.D_1R, SkyblueModTabs.TAB_SKYBLUE);
		EWATER_BUCKET = REGISTRY.register("ewater_bucket", EwaterItem::new);
		EGRASS = blockCMT(SkyblueModBlocks.EGRASS, SkyblueModTabs.TAB_SKYBLUE);
		EDIRT = blockCMT(SkyblueModBlocks.EDIRT, SkyblueModTabs.TAB_SKYBLUE);
		ESTONE = blockCMT(SkyblueModBlocks.ESTONE, SkyblueModTabs.TAB_SKYBLUE);
		EE_1 = blockCMT(SkyblueModBlocks.EE_1, SkyblueModTabs.TAB_SKYBLUE);
		FT_1 = blockCMT(SkyblueModBlocks.FT_1, SkyblueModTabs.TAB_SKYBLUE);
		FRR_1 = blockCMT(SkyblueModBlocks.FRR_1, SkyblueModTabs.TAB_SKYBLUE);
		FFR = blockCMT(SkyblueModBlocks.FFR, SkyblueModTabs.TAB_SKYBLUE);
		GREEN = blockCMT(SkyblueModBlocks.GREEN, SkyblueModTabs.TAB_SKYBLUE);
		RED_1 = blockCMT(SkyblueModBlocks.RED_1, SkyblueModTabs.TAB_SKYBLUE);
		GG_1 = blockCMT(SkyblueModBlocks.GG_1, SkyblueModTabs.TAB_SKYBLUE);
		RED_2 = blockCMT(SkyblueModBlocks.RED_2, SkyblueModTabs.TAB_SKYBLUE);
		GREEN_2 = blockCMT(SkyblueModBlocks.GREEN_2, SkyblueModTabs.TAB_SKYBLUE);
		GG_2 = blockCMT(SkyblueModBlocks.GG_2, SkyblueModTabs.TAB_SKYBLUE);
		GREEN_3 = blockCMT(SkyblueModBlocks.GREEN_3, SkyblueModTabs.TAB_SKYBLUE);
		RED_3 = blockCMT(SkyblueModBlocks.RED_3, SkyblueModTabs.TAB_SKYBLUE);
		GG_3 = blockCMT(SkyblueModBlocks.GG_3, SkyblueModTabs.TAB_SKYBLUE);
		GREEN_4 = blockCMT(SkyblueModBlocks.GREEN_4, SkyblueModTabs.TAB_SKYBLUE);
		RED_4 = blockCMT(SkyblueModBlocks.RED_4, SkyblueModTabs.TAB_SKYBLUE);
		GG_4 = blockCMT(SkyblueModBlocks.GG_4, SkyblueModTabs.TAB_SKYBLUE);
		GG_5 = blockCMT(SkyblueModBlocks.GG_5, SkyblueModTabs.TAB_SKYBLUE);
		GREEN_5 = blockCMT(SkyblueModBlocks.GREEN_5, SkyblueModTabs.TAB_SKYBLUE);
		RED_5 = blockCMT(SkyblueModBlocks.RED_5, SkyblueModTabs.TAB_SKYBLUE);
		PHOTO_1 = REGISTRY.register("photo_1", Photo1Item::new);
		WATERH_BUCKET = REGISTRY.register("waterh_bucket", WaterhItem::new);
		MUSH_1 = block(SkyblueModBlocks.MUSH_1, new Item.Properties().rarity(Rarity.UNCOMMON).isImmuneToFire().group(SkyblueModTabs.TAB_SKYBLUE));
		BLUE_1 = blockCMT(SkyblueModBlocks.BLUE_1, SkyblueModTabs.TAB_SKYBLUE);
		BLUE_2 = blockCMT(SkyblueModBlocks.BLUE_2, SkyblueModTabs.TAB_SKYBLUE);
		BLUE_3 = blockCMT(SkyblueModBlocks.BLUE_3, SkyblueModTabs.TAB_SKYBLUE);
		BLUE_4 = blockCMT(SkyblueModBlocks.BLUE_4, SkyblueModTabs.TAB_SKYBLUE);
		BLUE_5 = blockCMT(SkyblueModBlocks.BLUE_5, SkyblueModTabs.TAB_SKYBLUE);
		TWOTHREETWO = blockCMT(SkyblueModBlocks.TWOTHREETWO, SkyblueModTabs.TAB_SKYBLUE);
		I_LOG = blockCMT(SkyblueModBlocks.I_LOG, SkyblueModTabs.TAB_SKYBLUE);
		I_WOOD = blockCMT(SkyblueModBlocks.I_WOOD, SkyblueModTabs.TAB_SKYBLUE);
		I_PLANKS = blockCMT(SkyblueModBlocks.I_PLANKS, SkyblueModTabs.TAB_SKYBLUE);
		I_LEAVES = blockCMT(SkyblueModBlocks.I_LEAVES, SkyblueModTabs.TAB_SKYBLUE);
		I_STAIRS = blockCMT(SkyblueModBlocks.I_STAIRS, SkyblueModTabs.TAB_SKYBLUE);
		I_SLAB = blockCMT(SkyblueModBlocks.I_SLAB, SkyblueModTabs.TAB_SKYBLUE);
		I_FENCE = blockCMT(SkyblueModBlocks.I_FENCE, SkyblueModTabs.TAB_SKYBLUE);
		I_FENCE_GATE = blockCMT(SkyblueModBlocks.I_FENCE_GATE, SkyblueModTabs.TAB_SKYBLUE);
		I_PRESSURE_PLATE = blockCMT(SkyblueModBlocks.I_PRESSURE_PLATE, SkyblueModTabs.TAB_SKYBLUE);
		I_BUTTON = blockCMT(SkyblueModBlocks.I_BUTTON, SkyblueModTabs.TAB_SKYBLUE);
		ICOBBLESTONE = blockCMT(SkyblueModBlocks.ICOBBLESTONE, SkyblueModTabs.TAB_SKYBLUE);
		IDOORS = doubleBlockCMT(SkyblueModBlocks.IDOORS, SkyblueModTabs.TAB_SKYBLUE);
		ICOBBLESTONE_STAIRS = blockCMT(SkyblueModBlocks.ICOBBLESTONE_STAIRS, SkyblueModTabs.TAB_SKYBLUE);
		IP = blockCMT(SkyblueModBlocks.IP, SkyblueModTabs.TAB_SKYBLUE);
		JB_1 = blockCMT(SkyblueModBlocks.JB_1, SkyblueModTabs.TAB_SKYBLUE);
		JP = blockCMT(SkyblueModBlocks.JP, SkyblueModTabs.TAB_SKYBLUE);
		JP_2 = blockCMT(SkyblueModBlocks.JP_2, SkyblueModTabs.TAB_SKYBLUE);
		JP_3 = blockCMT(SkyblueModBlocks.JP_3, SkyblueModTabs.TAB_SKYBLUE);
		JP_4 = blockCMT(SkyblueModBlocks.JP_4, SkyblueModTabs.TAB_SKYBLUE);
		JB_2SEVENONE = blockCMT(SkyblueModBlocks.JB_2SEVENONE, SkyblueModTabs.TAB_SKYBLUE);
		KK_1 = blockCMT(SkyblueModBlocks.KK_1, SkyblueModTabs.TAB_SKYBLUE);
		KK_2 = blockCMT(SkyblueModBlocks.KK_2, SkyblueModTabs.TAB_SKYBLUE);
		KK_3 = blockCMT(SkyblueModBlocks.KK_3, SkyblueModTabs.TAB_SKYBLUE);
		KK_1_ONE_EIGHT_EIGHT = blockCMT(SkyblueModBlocks.KK_1_ONE_EIGHT_EIGHT, SkyblueModTabs.TAB_SKYBLUE);
		K_KBRICK = blockCMT(SkyblueModBlocks.K_KBRICK, SkyblueModTabs.TAB_SKYBLUE);
		K_KFLOOR = blockCMT(SkyblueModBlocks.K_KFLOOR, SkyblueModTabs.TAB_SKYBLUE);
		LL_1SNOW = blockCMT(SkyblueModBlocks.LL_1SNOW, SkyblueModTabs.TAB_SKYBLUE);
		LL_1ROCK = blockCMT(SkyblueModBlocks.LL_1ROCK, SkyblueModTabs.TAB_SKYBLUE);
		LWATER_BUCKET = REGISTRY.register("lwater_bucket", LwaterItem::new);
		L_LOG = blockCMT(SkyblueModBlocks.L_LOG, SkyblueModTabs.TAB_SKYBLUE);
		L_WOOD = blockCMT(SkyblueModBlocks.L_WOOD, SkyblueModTabs.TAB_SKYBLUE);
		L_PLANKS = blockCMT(SkyblueModBlocks.L_PLANKS, SkyblueModTabs.TAB_SKYBLUE);
		L_LEAVES = blockCMT(SkyblueModBlocks.L_LEAVES, SkyblueModTabs.TAB_SKYBLUE);
		L_STAIRS = blockCMT(SkyblueModBlocks.L_STAIRS, SkyblueModTabs.TAB_SKYBLUE);
		L_SLAB = blockCMT(SkyblueModBlocks.L_SLAB, SkyblueModTabs.TAB_SKYBLUE);
		L_FENCE = blockCMT(SkyblueModBlocks.L_FENCE, SkyblueModTabs.TAB_SKYBLUE);
		L_FENCE_GATE = blockCMT(SkyblueModBlocks.L_FENCE_GATE, SkyblueModTabs.TAB_SKYBLUE);
		L_PRESSURE_PLATE = blockCMT(SkyblueModBlocks.L_PRESSURE_PLATE, SkyblueModTabs.TAB_SKYBLUE);
		L_BUTTON = blockCMT(SkyblueModBlocks.L_BUTTON, SkyblueModTabs.TAB_SKYBLUE);
		LSAP = blockCMT(SkyblueModBlocks.LSAP, SkyblueModTabs.TAB_SKYBLUE);
		LW = block(SkyblueModBlocks.LW, new Item.Properties().rarity(Rarity.UNCOMMON).isImmuneToFire().group(SkyblueModTabs.TAB_SKYBLUE));
		MMMMMMM = blockCMT(SkyblueModBlocks.MMMMMMM, SkyblueModTabs.TAB_SKYBLUE);
		SHARD_14 = REGISTRY.register("shard_14", Shard14Item::new);
		MMP = blockCMT(SkyblueModBlocks.MMP, SkyblueModTabs.TAB_SKYBLUE);
		NNN = blockCMT(SkyblueModBlocks.NNN, SkyblueModTabs.TAB_SKYBLUE);
		NWATER_BUCKET = REGISTRY.register("nwater_bucket", NwaterItem::new);
		NLOG = blockCMT(SkyblueModBlocks.NLOG, SkyblueModTabs.TAB_SKYBLUE);
		NLOG_SLAB = blockCMT(SkyblueModBlocks.NLOG_SLAB, SkyblueModTabs.TAB_SKYBLUE);
		OC = blockCMT(SkyblueModBlocks.OC, SkyblueModTabs.TAB_SKYBLUE);
		OPLATE_1 = blockCMT(SkyblueModBlocks.OPLATE_1, SkyblueModTabs.TAB_SKYBLUE);
		OROCK_1 = blockCMT(SkyblueModBlocks.OROCK_1, SkyblueModTabs.TAB_SKYBLUE);
		OROCK_2 = blockCMT(SkyblueModBlocks.OROCK_2, SkyblueModTabs.TAB_SKYBLUE);
		OROCK_3 = blockCMT(SkyblueModBlocks.OROCK_3, SkyblueModTabs.TAB_SKYBLUE);
		OO = block(SkyblueModBlocks.OO, new Item.Properties().rarity(Rarity.EPIC).group(SkyblueModTabs.TAB_SKYBLUE));
		O_CC = blockCMT(SkyblueModBlocks.O_CC, SkyblueModTabs.TAB_SKYBLUE);
		PP = blockCMT(SkyblueModBlocks.PP, SkyblueModTabs.TAB_SKYBLUE);
		ONETWOFIVE = blockCMT(SkyblueModBlocks.ONETWOFIVE, null);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> blockCMT(RegistryObject<Block> block, ItemGroup tab) {
		return block(block, new Item.Properties().group(tab));
	}

	private static RegistryObject<Item> block(RegistryObject<Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}

	private static RegistryObject<Item> doubleBlockCMT(RegistryObject<Block> block, ItemGroup tab) {
		return doubleBlock(block, new Item.Properties().group(tab));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new TallBlockItem(block.get(), properties));
	}
}